### ISSUE TITLE
Launch pink agent with Bullet simulation

### ISSUE THREAD

**Issue by maximebrunet** [tasts-robots/upkie_locomotion#2]
Hello,

Congrats for this awsome project ! That's really inspiring and impressive how much can be done with the hardware/sefl-printed parts around these days!

I'm trying to test your pink agent in simulation, be I can't figure out how to make it launch, I'm hitting dependency issues, which I'm trying to solve one at one, but I'm new at bazel and not sure I'm even going the right way, could you help me please ?

I'm trying to launch it with the command:
```
./tools/bazelisk run -c opt //agents/pink_balancer:pink_balancer -- -c bullet
```
and I already added some dependencies
```
diff --git a/agents/pink_balancer/BUILD b/agents/pink_balancer/BUILD
index e48374f..1e07ff8 100644
--- a/agents/pink_balancer/BUILD
+++ b/agents/pink_balancer/BUILD
@@ -23,6 +23,8 @@ py_library(
         "@pip_upkie_locomotion//pypi__gin_config",
         # "@pip_upkie_locomotion//pypi__numpy",
         "@pip_upkie_locomotion//pypi__upkie_description",
+        "@pip_upkie_locomotion//pypi__isort",
+        "@pip_upkie_locomotion//pypi__pink",
     ],
 )
 
@@ -46,7 +48,9 @@ py_binary(
         ":whole_body_controller",
         "@mpacklog//:python",
         "@pip_upkie_locomotion//pypi__aiorate",
+        "@pip_upkie_locomotion//pypi__aiofiles",
         "@pip_upkie_locomotion//pypi__gin_config",
+        "@pip_upkie_locomotion//pypi__isort",
         "@vulp//spine:python",
     ],
 )
diff --git a/tools/workspace/pip_upkie_locomotion/requirements.txt b/tools/workspace/pip_upkie_locomotion/requirements.txt
index fe88628..9eeb308 100644
--- a/tools/workspace/pip_upkie_locomotion/requirements.txt
+++ b/tools/workspace/pip_upkie_locomotion/requirements.txt
@@ -6,3 +6,5 @@ msgpack>=0.6.2
 numpy>=1.21.2
 qpsolvers>=1.9.1
 upkie_description>=1.1.0
+pink==0.5.0
+isort
```
but I'm still getting this error when launching
```
raceback (most recent call last):
  File "/home/maxime/.cache/bazel/_bazel_maxime/f8d437c406d8a88179c45d5d834799cb/execroot/upkie_locomotion/bazel-out/k8-opt/bin/agents/pink_balancer/pink_balancer.runfiles/upkie_locomotion/agents/pink_balancer/main.py", line 34, in <module>
    from agents.pink_balancer.whole_body_controller import WholeBodyController
  File "/home/maxime/.cache/bazel/_bazel_maxime/f8d437c406d8a88179c45d5d834799cb/execroot/upkie_locomotion/bazel-out/k8-opt/bin/agents/pink_balancer/pink_balancer.runfiles/upkie_locomotion/agents/pink_balancer/whole_body_controller.py", line 23, in <module>
    import pink.models
ModuleNotFoundError: No module named 'pink.models'; 'pink' is not a package
```
Do you know what I missed ? Or am I going the wrong way ?

Thanks for your help!

**Comment by stephane-caron** [comment]
Hi, thanks for your feedback :slightly_smiling_face: For now installing Pink through Bazel's Python rules is blocked by  https://github.com/stack-of-tasks/pinocchio/issues/1715. One workaround for now is to pip-install system-wide, then run the agent like you do.

> but I'm still getting this error when launching

Aaaand the problem of getting out of Bazel is that, until this is fixed, we need to do the versioning ourselves :sweat: The version corresponding to the current master branch should be:

```
pip install pin-pink==0.4.0
```

**Comment by maximebrunet** [comment]
Thank you for your answer ! I will try the system wide install when I can then

**Comment by stephane-caron** [comment]
The pink agent has been updated to the latest version of pink (0.10.0). Closing this issue for now, feel free to re-open if you have further questions.
